"""Build the vocabulary and kanji companion file for each chapter.

Genki's chapter word lists are the publisher's editorial selection, so they are
generated into `l<NN>.vocab.md` next to each chapter and kept out of git. The
chapter file itself carries only a pointer and the counts, both of which are
safe to commit.

    python3 tools/sync_tables.py                 # every chapter
    python3 tools/sync_tables.py chapters/g2/l21.md

Run `tools/fetch_data.py` first on a fresh clone, since the datasets the tables
are built from are not committed either.
"""

import glob
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import build_kanji  # noqa: E402
import build_vocab  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

BOOK_NUMERAL = {1: "I", 2: "II"}
EMPTY_KANJI = "_No kanji introduced in this lesson._"

POINTER = (
    "_{count} entries. Generated into `{companion}` by tools/sync_tables.py, "
    "and not committed. See data/README.md._"
)


def companion_name(path):
    return os.path.basename(path).replace(".md", ".vocab.md")


def section_bounds(lines, heading):
    """Return (start, end) line indices for the body of a `## heading` section."""
    start = None
    for i, line in enumerate(lines):
        if line.strip() == f"## {heading}":
            start = i + 1
            break
    if start is None:
        raise SystemExit(f"no '## {heading}' section found")

    for j in range(start, len(lines)):
        if lines[j].startswith("## "):
            return start, j
    return start, len(lines)


def replace_section(lines, heading, body):
    start, end = section_bounds(lines, heading)
    return lines[:start] + [""] + body + [""] + lines[end:]


def vocab_table(lesson):
    rows = build_vocab.lesson_entries(lesson)
    cols = ("kanji", "kana", "romaji", "english", "pos")
    body = [
        "| " + " | ".join(build_vocab.cell(r[c]) for c in cols) + " |" for r in rows
    ]
    return build_vocab.HEADER + body, len(rows)


def kanji_table(lesson):
    try:
        rows = build_kanji.lesson_entries(lesson)
    except SystemExit as err:
        if "no kanji found" not in str(err):
            raise
        return [EMPTY_KANJI], 0

    body = [
        "| "
        + " | ".join(
            [
                build_kanji.cell(r["kanji"]),
                build_kanji.cell(r["readings"]),
                build_kanji.cell(r["meaning"]),
                build_kanji.cell("; ".join(r["examples"])),
            ]
        )
        + " |"
        for r in rows
    ]
    return build_kanji.HEADER + body, len(rows)


def set_count(lines, field, value):
    pattern = re.compile(rf"^{field}:\s*\d+\s*$")
    for i, line in enumerate(lines):
        if pattern.match(line):
            lines[i] = f"{field}: {value}"
            return
    raise SystemExit(f"frontmatter is missing '{field}'")


def frontmatter_value(text, field):
    match = re.search(rf"^{field}:\s*(.+?)\s*$", text, re.MULTILINE)
    return match.group(1) if match else None


def sync(path):
    with open(path, encoding="utf-8") as f:
        text = f.read()
    lines = text.split("\n")

    lesson = frontmatter_value(text, "lesson")
    book = frontmatter_value(text, "book")
    if lesson is None or book is None:
        raise SystemExit(f"{path}: frontmatter is missing 'book' or 'lesson'")
    lesson, book = int(lesson), int(book)

    vocab, vocab_count = vocab_table(lesson)
    kanji, kanji_count = kanji_table(lesson)

    companion = companion_name(path)
    title = frontmatter_value(text, "title") or ""
    payload = [
        "<!-- Generated by tools/sync_tables.py. Not committed, since these are",
        "     the textbook's own word lists. See data/README.md. -->",
        "",
        f"# Genki {BOOK_NUMERAL[book]} Lesson {lesson} ({title}) word lists",
        "",
        "## Vocabulary",
        "",
        *vocab,
        "",
        "## Kanji",
        "",
        *kanji,
        "",
    ]
    with open(os.path.join(os.path.dirname(path), companion), "w", encoding="utf-8") as f:
        f.write("\n".join(payload))

    for heading, count in (("Vocabulary", vocab_count), ("Kanji", kanji_count)):
        pointer = POINTER.format(count=count, companion=companion)
        lines = replace_section(lines, heading, [pointer])

    set_count(lines, "vocab_count", vocab_count)
    set_count(lines, "kanji_count", kanji_count)

    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    rel = os.path.relpath(path, ROOT)
    print(f"synced {rel} -> {companion} ({vocab_count} words, {kanji_count} kanji)")


def main():
    targets = sys.argv[1:] or sorted(
        glob.glob(os.path.join(ROOT, "chapters", "g*", "l[0-9][0-9].md"))
    )
    if not targets:
        raise SystemExit("no chapter files found")

    skipped = []
    for path in targets:
        try:
            sync(os.path.abspath(path))
        except SystemExit as err:
            # One chapter missing its metadata should not stop the rest.
            skipped.append(f"{os.path.relpath(path, ROOT)}: {err}")

    for note in skipped:
        print(f"SKIPPED {note}")
    if skipped:
        return 1
    return 0


if __name__ == "__main__":
    main()
